# 1초마다 기간이 지난 인증번호를 삭제하도록 이벤트를 등록
CREATE EVENT DELETE_CERITIFICATION
ON SCHEDULE EVERY 1 SECOND
DO
	DELETE FROM CERTIFICATION WHERE CE_LIMIT <= NOW();

# 이벤트 조회
SELECT * FROM information_schema.EVENTS;

# 이벤트 삭제
DROP EVENT DELETE_CERITIFICATION;

# 지정 시간에 이벤트가 1번만 실행되고 이벤트를 삭제 : NOT PRESERVE
CREATE EVENT DELETE_CERITIFICATION
ON SCHEDULE
AT '2024-02-15 09:40:00'
ON COMPLETION NOT PRESERVE
DO
	DELETE FROM CERTIFICATION WHERE CE_LIMIT <= NOW();
