
# DB 생성
DROP DATABASE IF EXISTS UNIVERSITY;
CREATE DATABASE IF NOT EXISTS UNIVERSITY;

USE UNIVERSITY;

# STUDENT TABLE 삭제 후 추가
DROP TABLE IF EXISTS STUDENT;
CREATE TABLE IF NOT EXISTS STUDENT(
	ST_NUM CHAR(10) PRIMARY KEY,
    ST_NAME VARCHAR(30) NOT NULL,
    ST_MAJOR VARCHAR(15) NOT NULL,
    ST_GRADE INT NOT NULL DEFAULT 1
);
DESC STUDENT;

# PROFESSOR TABLE 삭제 후 추가
DROP TABLE IF EXISTS PROFESSOR;
CREATE TABLE IF NOT EXISTS PROFESSOR(
	PR_NUM CHAR(10) PRIMARY KEY,
    PR_NAME VARCHAR(30) NOT NULL,
    PR_ROOM VARCHAR(100),
    PR_MAJOR VARCHAR(15) NOT NULL
);
DESC PROFESSOR;

# LECTURE TABLE 삭제 후 추가
DROP TABLE IF EXISTS LECTURE;
CREATE TABLE IF NOT EXISTS LECTURE(
	LE_NUM INT PRIMARY KEY AUTO_INCREMENT,
    LE_TITLE VARCHAR(30) NOT NULL,
    LE_ROOM VARCHAR(20),
    LE_SHCEDULE VARCHAR(50) NOT NULL,
    LE_POINT INT NOT NULL DEFAULT 0,
    LE_TIME INT NOT NULL DEFAULT 0,
    LE_PR_NUM CHAR(10),
    FOREIGN KEY (LE_PR_NUM) REFERENCES PROFESSOR(PR_NUM)
);
DESC LECTURE;

# COURSE TABLE 삭제 후 추가
DROP TABLE IF EXISTS COURSE;
CREATE TABLE IF NOT EXISTS COURSE(
	CO_NUM INT PRIMARY KEY AUTO_INCREMENT,
    CO_ST_NUM CHAR(10) NOT NULL,
    CO_LE_NUM INT NOT NULL,
    FOREIGN KEY (CO_ST_NUM) REFERENCES STUDENT(ST_NUM),
    FOREIGN KEY (CO_LE_NUM) REFERENCES LECTURE(LE_NUM)
);
DESC COURSE;

# CONTACT TABLE 삭제 후 추가
DROP TABLE IF EXISTS CONTACT;
CREATE TABLE IF NOT EXISTS CONTACT(
	CT_ST_NUM CHAR(10) PRIMARY KEY,
    CT_PHONE VARCHAR(13) NOT NULL,
    CT_ADDR VARCHAR(30) NOT NULL,
    CT_DETAIL VARCHAR(30) NOT NULL DEFAULT "",
    FOREIGN KEY (CT_ST_NUM) REFERENCES STUDENT(ST_NUM)
);
DESC CONTACT;

